In [2]:
import pandas as pd
import re

In [3]:
df=pd.read_excel('data.xlsx')

In [4]:
df

,global_index,Length,SCV,Description,Sentences,ACMG_Codes,Keywords_inclusion,Keywords_exclusion,Remarks,Corrected_Attribute,Validated
0,35421,17,SCV001170543.3,Other strong data,Other strong data,['unknown'],NaN,NaN,NaN,NaN,NaN
1,102577,20,SCV005020087.1,Elaine has saved RD.,Elaine has saved RD.,['unknown'],NaN,NaN,NaN,NaN,NaN
2,264484,31,SCV002672085.2,The c.737_739delTAG variant (also known as p.V...,Valine at codon 246 is deleted.,['unknown'],NaN,NaN,NaN,NaN,NaN
3,5414,33,SCV005022010.1,ASSESSED FOR SOMATIC SAMPLE ONLY. FOR ANY GERM...,ASSESSED FOR SOMATIC SAMPLE ONLY.,['unknown'],NaN,NaN,NaN,NaN,NaN
4,22765,35,SCV002722155.3,The p.P654L pathogenic mutation (also known as...,Similar results were seen in yeast.,['unknown'],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
14061,10403,579,SCV002607110.3,The c.3347-1G>A intronic variant results from ...,"In addition, this alteration has been detected...",['unknown'],NaN,NaN,NaN,NaN,NaN
14062,13339,580,SCV000262906.8,The c.815-27T>C intronic alteration consists o...,Functional analysis of cultured fibroblasts fr...,['unknown'],NaN,NaN,NaN,NaN,NaN
14063,226256,589,SCV003602117.2,The c.2638C>T (p.R880C) alteration is located ...,This alteration was reported de novo in an ind...,['PS2'],NaN,NaN,NaN,NaN,NaN
14064,26904,597,SCV000666873.6,"The p.S382I variant (also known as c.1145G>T),...","Across multiple studies, this alteration has b...",['unknown'],NaN,NaN,NaN,NaN,NaN
14065,6522,645,SCV002719153.2,"The c.188delC variant, located in coding exon ...",Protein analysis demonstrated 2 mutant PDX1 pr...,['PS3'],NaN,NaN,NaN,NaN,NaN

In [33]:
def cleanup(x):
    try:
        return eval(x)
    except:
        data = re.split(r'[,+ .]', x)
        cleaned = [x for x in data if x not in ['','(automated)','or']]
        return cleaned

In [35]:
df['Corrected_Attribute']=df['Corrected_Attribute'].map(cleanup)

In [50]:
count=0
for i in df['Corrected_Attribute']:
    if i[0] in ['Unkown','Unkknown']:
        print(count)
    count+=1

39
47

In [54]:
df.iloc[[39,47],:]

,Unnamed: 0,Description,Corrected_Attribute,class
39,1054,The p.C3233F variant (also known as c.9698G>T)...,[Unkown],NaN
47,1369,The p.E2663V pathogenic mutation (also known a...,[Unkknown],NaN

In [55]:
df = df.drop(df.iloc[[39, 47]].index)

In [56]:
df

,Unnamed: 0,Description,Corrected_Attribute,class
0,228,"The c.1147dupC (p.H383Pfs*103) alteration, loc...",[PS3],Pathogenic
1,233,The p.A2603T variant (also known as c.7807G>A)...,[BS3],Benign
2,249,"The p.L21P variant (also known as c.62T>C), lo...",[PM6],Pathogenic
3,283,The c.125-9831_236del9943 gross deletion inclu...,[PS3],Pathogenic
4,336,The p.M3118T variant (also known as c.9353T>C)...,[PP1],Pathogenic
...,...,...,...,...
273,13961,The c.1212A>C variant (also known as p.*404CEX...,[PS1],Pathogenic
274,13983,The c.1921A>G (p.N641D) alteration is located ...,[PS1],Pathogenic
275,14026,"The c.862_863delCA pathogenic mutation, locate...","[BP2, PS3]",Both
276,14045,"The p.L622R variant (also known as c.1865T>G),...",[PS1],Pathogenic
277,14060,The p.Q475* pathogenic mutation (also known as...,"[BP2, PS3]",Both

In [57]:
df.to_csv(r"C:\Users\rishi\Desktop\Personal\Testing\final_classification.csv")

In [59]:
df

,Unnamed: 0.1,Unnamed: 0,Description,Corrected_Attribute,class
0,0,228,"The c.1147dupC (p.H383Pfs*103) alteration, loc...",['PS3'],Pathogenic
1,1,233,The p.A2603T variant (also known as c.7807G>A)...,['BS3'],Benign
2,2,249,"The p.L21P variant (also known as c.62T>C), lo...",['PM6'],Pathogenic
3,3,283,The c.125-9831_236del9943 gross deletion inclu...,['PS3'],Pathogenic
4,4,336,The p.M3118T variant (also known as c.9353T>C)...,['PP1'],Pathogenic
...,...,...,...,...,...
271,273,13961,The c.1212A>C variant (also known as p.*404CEX...,['PS1'],Pathogenic
272,274,13983,The c.1921A>G (p.N641D) alteration is located ...,['PS1'],Pathogenic
273,275,14026,"The c.862_863delCA pathogenic mutation, locate...","['BP2', 'PS3']",Both
274,276,14045,"The p.L622R variant (also known as c.1865T>G),...",['PS1'],Pathogenic
275,277,14060,The p.Q475* pathogenic mutation (also known as...,"['BP2', 'PS3']",Both